### ISSUE TITLE
Add UI to view documentation

### ISSUE THREAD

**Issue by tehmantra** [tehmantra/saunter#28]
Similar to Swachbuckle.AspNetCore which provides `app.UseSwaggerUI()` it would be nice to have an `app.UseAsyncApiUI()`

**Comment by tscrypter** [comment]
I'll take this one as well. Any particular UI, or should I simply mirror the SwaggerUI and possibly theme it differently?

**Comment by tehmantra** [comment]
I don't really have a preference for how to do this one. Using the official asyncapi template seems like a great idea!
Ideally this all gets packaged up nicely in the NuGet package, and from the users perspective they just add 1 line of code and get a nice UI out of it.

**Comment by tehmantra** [comment]
Not sure how you're getting on with this one, but I had an idea which is kind of a hack/cheating, but would be very simple.

AsyncAPI Playground (https://playground.asyncapi.io/) accepts a query parameter `load`, which is the URL of an asyncapi document to load.
In our case, linking to `https://playground.asyncapi.io/?load=http://localhost:5000/asyncapi/asyncapi.json` will load the document from our API and render it successfully.

![image](https://user-images.githubusercontent.com/3260812/95189002-c3683580-0829-11eb-9853-2d5858c4a444.png)

If dynamically building the UI turns out to be too complex, this would be an acceptable compromise.

**Comment by tscrypter** [comment]
I actually started by implementing this approach, so I'll revert my work since that working commit, add some tests and issue a PR. I'll also add some documentation about the dependency on the AsyncAPI Playground.

I'll make the extension method `app.UseAsyncApiUI()` default to the public AsyncAPI Playground, and also provide a `app.UseAsyncApiUI(playgroundBaseUri)` for those that want to run their services internally in a firewall and limit external internet access for security reasons.

I wouldn't call it a 'hack' as much as I'd say it's following a **microservice** architecture to keep the library thin :wink:

**Comment by tscrypter** [comment]
I'm making progress on this, though I've run into a bit of a headache in terms of serving the css/js for index.html. I'm able to effectively proxy the request to a running instance of **playground** (I'm actually making an API call to the `http://playground/html/generate` method call which returns a full html page), and that renders the doc without styles/javascript (subsequent calls from the browser fails). 

My first attempt at solving this issue is to try and match on `http://localhost:5000/asyncapi/ui/**/*` and just proxy those requests to `http://playground/**/*`. This in my mind would be the ideal so that if the html is updated with new styles, it'll automatically be served.
