### ISSUE TITLE
Missing default property in Schema class.

### ISSUE THREAD

**Issue by fglaeser** [tehmantra/saunter#7]
Another topic. I was using the classes to generate yaml documentation, that is why a found some missing properties. 
It will be good to have yaml generation also, What do you think?

Facundo

**Comment by tehmantra** [comment]
I'm investigating how to achieve this now.
All the types are currently annotated with `[JsonProperty("name")]` and it would be nice to just have 1 attribute rather than `[JsonProperty][YamlMember]`.

Seems like you can use `[DataMember(Name = "name")]` for Json.NET, but that doesn't work for YamlDotNet. I'll do some more digging.

**Comment by fglaeser** [comment]
There is an Open issue already.
https://github.com/aaubry/YamlDotNet/issues/461

**Comment by tehmantra** [comment]
It seems like neither System.Text.Json nor YamlDotNet are interested in using a standard attribute like `[DataMember]`.
YAML generation will require adding some YAML serializer as a dependency which I'd like to avoid.

This could be achieved by a client by passing the generated JSON to a JSON-to-YAML converter, or using the `IAsyncApiDocumentProvider.GetDocument()` method and serializing the object to YAML.
