### ISSUE TITLE
MapAsyncApiDocuments not found

### ISSUE THREAD

**Issue by rasert** [tehmantra/saunter#95]
Documentation says that I should add this

app.UseEndpoints(endpoints =>
{
    endpoints.MapAsyncApiDocuments();
});

But there is no MapAsyncApiDocuments extension method on v0.2.0 package. I am running .Net 5.

**Comment by gustavoosantoos** [comment]
I'm having the same problem here. :( 
@tehmantra could you help us please?

**Comment by Rikj000** [comment]
@rasert and @gustavoosantoos, I experienced the same issue but managed to resolve it.   

The reason behind this is that the [`v0.2.0`](https://github.com/tehmantra/saunter/releases/tag/v0.2.0) Release is nearly a year old, and it doesn't contain all the latest commits!

The solution was to remove the `NuGet` package, then `git clone` the **Saunter** project and finally reference it as a dependency in your own project.

@tehmantra, I don't know if there are any well-known issues holding you back, but if not I'd consider pushing out a new release so these questions won't arise again! 🙂

**Comment by gustavoosantoos** [comment]
> @rasert and @gustavoosantoos, I experienced the same issue but managed to resolve it.
> 
> The reason behind this is that the [`v0.2.0`](https://github.com/tehmantra/saunter/releases/tag/v0.2.0) Release is nearly a year old, and it doesn't contain all the latest commits!
> 
> The solution was to remove the `NuGet` package, then `git clone` the **Saunter** project and finally reference it as a dependency in your own project.
> 
> @tehmantra, I don't know if there are any well-known issues holding you back, but if not I'd consider pushing out a new release so these questions won't arise again! 🙂

I had to do the same, and published the package on a private nuget feed. 
I am planning to making my fork public available in a new, public nuget package.

**Comment by tehmantra** [comment]
Hey, sorry for the delay here. I've not been the most active maintainer.
I've just published v0.3.0 now https://www.nuget.org/packages/Saunter/0.3.0

If you have time to help work the package, I am open to accepting maintainers 🙂
I think it's best to keep everything in 1 package rather than creating forks if possible.

**Comment by gustavoosantoos** [comment]
> Hey, sorry for the delay here. I've not been the most active maintainer.
> I've just published v0.3.0 now https://www.nuget.org/packages/Saunter/0.3.0
> 
> If you have time to help work the package, I am open to accepting maintainers 🙂
> I think it's best to keep everything in 1 package rather than creating forks if possible.

I agree, but 50 days without any response, it's not viable for any open source project. It seemed an abandoned project.

**Comment by tehmantra** [comment]
Yep I agree. I will be taking a more active role as a maintainer now.On Tue, Jul 20, 2021 at 12:09 AM, Gustavo Santos ***@***.***> wrote:  

Hey, sorry for the delay here. I've not been the most active maintainer.
I've just published v0.3.0 now https://www.nuget.org/packages/Saunter/0.3.0
If you have time to help work the package, I am open to accepting maintainers 🙂
I think it's best to keep everything in 1 package rather than creating forks if possible.

I agree, but 50 days without any response, it's not viable for any open source project. It seemed an abandoned project.
